name: Deploy to GitHub Pages

# Run workflow on every push to master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
      run: rm ${{ env.WEBAPP_PATH }}/Properties/launchSettings.json
    - name: Tailwind - download and run cli
      run: |
        wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
        chmod +x /usr/local/bin/tailwindcss
        cd ${{ env.WEBAPP_PATH }}
        tailwindcss --input ./wwwroot/app.css  --output ./wwwroot/app.min.css  --minify

    - name: Run webapp and generate static files
      run: dotnet run --project Nikolei.Blog/Nikolei.Blog.csproj  --configuration Release

    - name: Upload webapp output artifacts
      uses: actions/upload-artifact@v4
      with:
          name: static-pages-output
          path: Nikolei.Blog/output

