name: Deploy to GitHub Pages

# Run workflow on every push to master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 9.x
    - name: Publish .NET Core Project
      run: dotnet publish Nikolei.Blog/Nikolei.Blog.csproj -c Release -o release --nologo
