
name: Build, publish to gh pages and nuget

on:
  push:
    branches:
      - main

env:
  WEBAPP_PATH: Nikolei.Blog
  WEBAPP_CSPROJ: Nikolei.Blog.csproj
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      webapp-path: ${{ env.WEBAPP_PATH }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
        run: rm ${{ env.WEBAPP_PATH }}/Properties/launchSettings.json
      - name: Tailwind - download and run cli
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
          cd ${{ env.WEBAPP_PATH }}
          tailwindcss --input ./wwwroot/app.css  --output ./wwwroot/app.min.css  --minify

      - name: Run webapp and generate static files
        run: dotnet run --project ${{ env.WEBAPP_PATH }}/${{env.WEBAPP_CSPROJ}}  --configuration Release

      - name: Upload webapp output artifacts
        uses: actions/upload-artifact@v4
        with:
            name: static-pages-output
            path: ${{ env.WEBAPP_PATH }}/output


  deploy-to-gh-pages:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: static-pages-output
          path: output
      - run: touch output/.nojekyll #folder starting with _ are handled as jekyll. This file will prevent that.
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./output
