name: Deploy to GitHub Pages

# Run workflow on every push to master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Run webapp and generate static files
      run: dotnet run --project Nikolei.Blog/Nikolei.Blog.csproj  --configuration Release

    - name: Upload webapp output artifacts
      uses: actions/upload-artifact@v4
      with:
          name: static-pages-output
          path: Nikolei.Blog/output

